# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: tags/
    weight: 20
  - name: CV
    url: uses/
    weight: 30
