# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: CV
    url: /uploads/CV.pdf
    weight: 20
  - name: Research
    url: /blog/
    weight: 30
