# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: /studies/
    weight: 20
  - name: CV
    url: /cv/
    weight: 30
